# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e862d03874c348f048a2eed7ad109aae559b0d2cfee22bd95addec30848bce78d944404bf860da72c5511155435df1e26f1e342d22784a014b93f64fc8775af2

test:
  secret_key_base: 361811ea4749c4999c6f51d65967cce7a6544e6e9c78ac170630c30ba0d2a1ba4acf48b4cbb53cc1a93599157a63f5ee28517b3ca919134893499a8905f6267a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
